{{- define "common-eap.buildconfig-app-s2i.tpl" -}}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "common-eap.appName" . }}
  labels:
    {{- include "common-eap.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
  source:
    type: Docker
    images:
    - from:
        kind: ImageStreamTag
        name: {{ include "common-eap.appBuilderImage" . }}:latest
      paths:
      - destinationDir: .
        sourcePath: /s2i-output/server/
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
      imageOptimizationPolicy: SkipLayers
    type: Docker
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: {{ include "common-eap.appBuilderImage" . }}:latest
    type: ImageChange
  - type: ConfigChange
{{- end -}}
{{- define "common-eap.buildconfig-app-s2i" -}}
{{- include "common-eap.util.merge" (append . "common-eap.buildconfig-app-s2i.tpl") -}}
{{- end -}}