{{- define "common-eap.deploymentconfig" -}}
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ include "common-eap.appName" . }}
  labels:
  {{- include "common-eap.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ include "common-eap.appName" . }}
        from:
          kind: ImageStreamTag
          name: {{ include "common-eap.appName" . }}:latest
    - type: ConfigChange
  replicas: {{ .Values.deploy.replicas }}
  selector:
    {{- include "common-eap.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      name: {{ include "common-eap.appName" . }}
      labels:
      {{- include "common-eap.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "common-eap.appName" . }}
          image: {{ include "common-eap.appName" . }}
          imagePullPolicy: Always
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: ping
            containerPort: 8888
            protocol: TCP
          - name: admin
            containerPort: 9990
            protocol: TCP
          {{- if .Values.deploy.resources }}
          resources:
            {{- toYaml .Values.deploy.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .Values.deploy.livenessProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .Values.deploy.readinessProbe) . | nindent 12 }}
          {{- end }}
          {{- if (lookup "v1" "Secret" .Release.Namespace "eap-extensions") }}
          volumeMounts:
          - name: eap-extensions
            mountPath: /etc/eap-environment/
            readOnly: true
          {{- end }}
          env:
          - name: JGROUPS_PING_PROTOCOL
            value: dns.DNS_PING
          - name: OPENSHIFT_DNS_PING_SERVICE_PORT
            value: '8888'
          - name: AUTO_DEPLOY_EXPLODED
            value: 'false'
          - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
            value: 'false'
          - name: OPENSHIFT_DNS_PING_SERVICE_NAME
            value: {{ include "common-eap.appName" . }}-ping
          - name: ENV_FILES
            value: /etc/eap-environment/*
          {{- if .Values.deploy.env }}
          {{- tpl (toYaml .Values.deploy.env) . | nindent 10 }}
          {{- end }}
          {{- if .Values.deploy.envFrom }}
          envFrom:
          {{- tpl (toYaml .Values.deploy.envFrom) . | nindent 10 }}
          {{- end }}
      {{- if (lookup "v1" "Secret" .Release.Namespace "eap-extensions") }}
      volumes:
      - name: eap-extensions
        secret:
          secretName: eap-extensions
      {{- end }}
{{- end -}}