{{- define "common-eap.imagestream" -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "common-eap.appName" . }}
  labels:
{{- include "common-eap.labels" . | nindent 4 }}
{{- end -}}