# Default values for wildfly
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

build:
  s2i:
    jdk: "11"
    jdk8:
      builderImageStream: jboss-eap-xp2-openjdk8-openshift:2.0
      runtimeImageStream: jboss-eap-xp2-openjdk8-runtime-openshift:2.0
    jdk11:
      builderImageStream: jboss-eap-xp2-openjdk11-openshift:2.0
      runtimeImageStream: jboss-eap-xp2-openjdk11-runtime-openshift:2.0