{{- include "common-eap.buildconfig-app-s2i" (list . "eap-xp2.buildconfig-app-s2i") -}}
{{- define "eap-xp2.buildconfig-app-s2i" -}}
spec:
  source:
    dockerfile: |-
      FROM {{ include "eap-xp2.eapRuntimeImage" . }}
      COPY /server $JBOSS_HOME
      USER root
      RUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME
      USER jboss
      CMD $JBOSS_HOME/bin/openshift-launch.sh
  strategy:
    dockerStrategy:
      from:
        name: {{ include "eap-xp2.eapRuntimeImage" . }}
{{- end -}}
