{{- if and .Values.build.enabled (eq .Values.build.mode "bootable-jar") }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "wildfly.appName" . }}
  labels:
{{- include "wildfly.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "wildfly.appName" . }}:latest
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: java:11
      {{- if .Values.build.env }}
      env:
        {{- tpl (toYaml .Values.build.env) . | nindent 8 }}
      {{- end }}
  source:
    type: Git
    git:
      ref: {{ .Values.build.ref }}
      uri: {{ required "Git source repository URL is required" .Values.build.uri }}
    {{- if .Values.build.contextDir }}
    contextDir: {{ .Values.build.contextDir }}
    {{- end }}
    {{- if .Values.build.images }}
    images:
      {{- tpl (toYaml .Values.build.images) . | nindent 6 }}
    {{- end}}
  {{- if .Values.build.resources }}
  resources:
    {{- toYaml .Values.build.resources | nindent 4 }}
  {{- end }}
  triggers:
    - type: ConfigChange
  runPolicy: Serial
{{- end }}