kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ include "wildfly.appName" . }}
  labels:
  {{- include "wildfly.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ include "wildfly.appName" . }}
        from:
          kind: ImageStreamTag
          namespace: default
          name: {{ include "wildfly.appName" . }}:latest
    - type: ConfigChange
  replicas: {{ .Values.deploy.replicas }}
  selector:
    {{- include "wildfly.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      name: {{ include "wildfly.appName" . }}
      labels:
      {{- include "wildfly.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "wildfly.appName" . }}
          image: {{ include "wildfly.appName" . }}
          imagePullPolicy: Always
          ports:
          {{- range .Values.deploy.ports }}
          - name: {{ .name }}
            containerPort: {{ .containerPort }}
            protocol: {{ .protocol }}
          {{- end }}
          {{- if .Values.deploy.resources }}
          resources:
            {{- toYaml .Values.deploy.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .Values.deploy.livenessProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .Values.deploy.readinessProbe) . | nindent 12 }}
          {{- end }}
          env:
          - name: OPENSHIFT_DNS_PING_SERVICE_NAME
            value: {{ include "wildfly.appName" . }}-ping
          {{- if .Values.deploy.internalEnv }}
          {{- tpl (toYaml .Values.deploy.internalEnv) . | nindent 10 }}
          {{- end }}
          {{- if .Values.deploy.env }}
          {{- tpl (toYaml .Values.deploy.env) . | nindent 10 }}
          {{- end }}
          {{- if .Values.deploy.envFrom }}
          envFrom:
          {{- tpl (toYaml .Values.deploy.envFrom) . | nindent 10 }}
          {{- end }}