# Default values for wildfly
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

wildfly:
  version: "22.0"
build:
  mode: bootable-jar
  enabled: true
deploy:
  route:
    enabled: true
  livenessProbe:
    httpGet:
        path: /health/live
        port: admin
  readinessProbe:
    httpGet:
        path: /health/ready
        port: admin