build:
  mode: bootable-jar
  uri: https://github.com/wildfly/quickstart.git
  ref: 22.0.0.Final
  env:
  - name: ARTIFACT_DIR
    value: microprofile-config/target
  - name: MAVEN_OPTS
    value: -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=512m
  - name: MAVEN_ARGS_APPEND
    value: -am -pl microprofile-config -Pbootable-jar
deploy:
  replicas: 3
  env:
  - name: CONFIG_PROP
    value: Hello from OpenShift