apiVersion: v2
name: eap73
description: Build and Deploy EAP 7.3 applications on OpenShift
type: application
version: 0.1.0

appVersion: "7.3"

dependencies:
- name: wildfly-common
  version: 0.1.0
  #repository: https://jmesnil.github.io/wildfly-charts/
  # for local development
  repository: file://../../../wildfly-charts/charts/wildfly-common
