# Default values for wildfly
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

build:
  enabled: true
  mode: s2i
  s2i:
    jdk: "11"
    jdk8:
      builderImageStream: jboss-eap73-openjdk8-openshift:7.3
      runtimeImageStream: jboss-eap73-openjdk8-runtime-openshift:7.3    
    jdk11:
      builderImageStream: jboss-eap73-openjdk11-openshift:7.3
      runtimeImageStream: jboss-eap73-openjdk11-runtime-openshift:7.3
deploy:
  route:
    enabled: true
  livenessProbe:
    exec:
      command:
        - /bin/bash
        - -c
        - /opt/eap/bin/livenessProbe.sh
    initialDelaySeconds: 60
  readinessProbe:
    exec:
      command:
        - /bin/bash
        - -c
        - /opt/eap/bin/readinessProbe.sh
    initialDelaySeconds: 10
