{{- if and .Values.build.enabled (eq .Values.build.mode "s2i") }}
{{- include "wildfly-common.buildconfig-s2i-build-artifacts" (list . "eap73.buildconfig-s2i-build-artifacts") -}}
{{- end -}}

{{- define "eap73.buildconfig-s2i-build-artifacts" -}}
{{ include "eap73.metadata.labels" . }}
spec:
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ include "eap73.eapBuilderImage" . }}
{{- end -}}