{{- if and .Values.build.enabled (eq .Values.build.mode "s2i") }}
{{- include "wildfly-common.buildconfig-s2i-build-artifacts" (list . "eap73.buildconfig-s2i-build-artifacts") -}}
{{- end -}}

{{- define "eap73.buildconfig-s2i-build-artifacts" -}}
metadata:
  labels:
    {{- include "eap73.labels" . | nindent 4 }}
spec:
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ include "eap73.eapBuilderImage" . }}
{{- end -}}