{{- include "common-eap.buildconfig-app-s2i-build-artifacts" (list . "eap73.buildconfig-app-s2i-build-artifacts") -}}
{{- define "eap73.buildconfig-app-s2i-build-artifacts" -}}
spec:
  strategy:
    sourceStrategy:
      from:
        name: {{ include "eap73.eapBuilderImage" . }}
{{- end -}}
