{{- if .Values.build.enabled -}}
{{- include "wildfly-common.imagestream" (list . "eap73.metadata.labels") }}

{{- if eq .Values.build.mode "s2i" }}
---
{{- include "wildfly-common.imagestream-s2i-build-artifacts" (list . "eap73.metadata.labels") }}
{{- end -}}
{{- end -}}