{{- if .Values.build.enabled -}}
{{- include "wildfly-common.imagestream" (list . "eap.imagestream") -}}
{{- end -}}

{{- define "eap.imagestream" -}}
metadata:
  name: {{ include "wildfly-common.appImage" . }}
  labels:
    {{- include "eap73.labels" . | nindent 4 }}
{{- end -}}
