{{- if (and .Values.deploy.enabled .Values.deploy.route.enabled) }}
{{- include "wildfly-common.route" (list . "eap73.route") -}}
{{- end -}}

{{- define "eap73.route" -}}
metadata:
  labels:
  {{- include "eap73.labels" . | nindent 4 }}
{{- end -}}
