{{- if (and .Values.deploy.enabled .Values.deploy.route.enabled) }}
{{- include "wildfly-common.route" (list . "eap73.route") -}}
{{- end -}}

{{- define "eap73.route" -}}
metadata:
  name: {{ include "eap73.appName" . }}
  labels:
  {{- include "eap73.labels" . | nindent 4 }}
spec:
  to:
    name: {{ include "eap73.appName" . }}
{{- end -}}
