kind: ImageStream
apiVersion: v1
metadata:
  name: wildfly-runtime
{{ define wildflyQuayImage "quay.io/wildfly/wildfly-runtime-centos7"}}
spec:
  tags:
  - name: latest
    annotations:
      description: wildfly-runtime image stream
      iconClass: icon-wildfly
      tags: java,widlfly
      version: 'latest'
    from:
      kind: DockerImage
      name: {{ cat $wildflyQuayImage ":latest" | quote }}
  - name: {{ quote .Release.appVersion }}
    annotations:
      description: wildfly-runtime image stream
      iconClass: icon-wildfly
      tags: java,widlfly
      version: {{ quote .Release.appVersion }}
    from:
      kind: DockerImage
      name: {{ cat $wildflyQuayImage ":" .Release.appVersion | quote }}
---



apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "wildfly.appname" . }}
  labels:
{{- include "wildfly.labels" . | nindent 4 }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "wildfly.appname" . }}:latest
  source:
    dockerfile: |-
      FROM wildfly-runtime-centos7:{{ include "wildfly.version" . }}
      COPY /server $JBOSS_HOME
      USER root
      RUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME
      RUN ln -s $JBOSS_HOME /wildfly 
      USER jboss
      CMD $JBOSS_HOME/bin/openshift-launch.sh
    images:
      - from: 
          kind: ImageStreamTag
          name: {{ include "wildfly.appname" . }}-build-artifacts
        paths: 
        - sourcePath: /s2i-output/server/
          destinationDir: "."
  strategy:
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      from:
        kind: ImageStreamTag
        name: wildfly-runtime:{{ include "wildfly.version" . }}
        namespace: {{ .Values.wildfly.namespace }}
    type: Docker
  triggers:
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: {{ include "wildfly.appname" . }}-build-artifacts
  - type: ConfigChange




#---
# apiVersion: build.openshift.io/v1
# kind: BuildConfig
# metadata:
#   name: {{ include "wildfly.appname" . }}
#   labels:
# {{- include "wildfly.labels" . | nindent 4 }}
# spec:
#   output:
#     to:
#       kind: ImageStreamTag
#      name: {{ include "wildfly.appname" . }}:latest
#   source:
#     dockerfile: |-
#       FROM wildfly-runtime-centos7:{{ include "wildfly.version" . }}
#       COPY /server $JBOSS_HOME
#       USER root
#       RUN chown -R jboss:root $JBOSS_HOME && chmod -R ug+rwX $JBOSS_HOME
#       RUN ln -s $JBOSS_HOME /wildfly 
#       USER jboss
#       CMD $JBOSS_HOME/bin/openshift-launch.sh
#     images:
#       - from: 
#           kind: ImageStreamTag
#           name: {{ include "wildfly.appBuilderImage" . }}:latest
#         paths: 
#         - sourcePath: /s2i-output/server/
#           destinationDir: "."
#   strategy:
#     dockerStrategy:
#       imageOptimizationPolicy: SkipLayers
#       from:
#         kind: ImageStreamTag
#         name: wildfly-runtime:{{ include "wildfly.version" . }}
#         namespace: {{ .Values.wildfly.namespace }}
#     type: Docker
#   triggers:
#   - type: ImageChange
#     imageChange:
#       from:
#         kind: ImageStreamTag
#         name: {{ include "wildfly.appBuilderImage" . }}:latest
#   - type: ConfigChange